services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ezship-prod:latest
    container_name: ezship-app-prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://ezship.app
      - API_URL=https://api.ezship.app
      - EXTERNAL_NGINX=true
    depends_on:
      - postgres
      - redis
    networks:
      - ezship-network
    expose:
      - "9000"
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  postgres:
    image: postgres:15-alpine
    container_name: ezship-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-ezship_production}
      POSTGRES_USER: ${DB_USERNAME:-ezship_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - ezship-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-ezship_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ezship-redis-prod
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis-prod-data:/data
    expose:
      - "6379"
    networks:
      - ezship-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: ezship-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites:/etc/nginx/sites-available:ro
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - app
    networks:
      - ezship-network

networks:
  ezship-network:
    driver: bridge

volumes:
  postgres-prod-data:
    driver: local
  redis-prod-data:
    driver: local
  nginx-cache:
    driver: local